id: 9e3df74c6388448e8da53a40dde6ccc8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_152-The_Questions_of_Sagaramati-v2
  language: bo
  author: ''
  volume: {}
